/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;

/**
 *
 * @author ALLEXPA
 */
public class View_DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form View_DashBoard
     */
    public View_DashBoard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanal = new javax.swing.JPanel();
        headPanal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        optionPanal = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnTeacher = new javax.swing.JButton();
        btnExam = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnStaff = new javax.swing.JButton();
        bodyPanal = new javax.swing.JPanel();
        mainTab = new javax.swing.JTabbedPane();
        HomeTab = new javax.swing.JTabbedPane();
        homePanal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        StudentTab = new javax.swing.JTabbedPane();
        St_Home = new javax.swing.JTabbedPane();
        St_All = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        st_1 = new javax.swing.JPanel();
        St_btn_addmition = new javax.swing.JButton();
        st_2 = new javax.swing.JPanel();
        St_btn_Deatils = new javax.swing.JButton();
        st_3 = new javax.swing.JPanel();
        st_btn_result_in = new javax.swing.JButton();
        St_4 = new javax.swing.JPanel();
        st_btn_result_out = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        St_Admition = new javax.swing.JTabbedPane();
        st_admision_main_pan = new javax.swing.JPanel();
        st_add = new javax.swing.JPanel();
        Table_Student = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel28 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        St_deatils = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jLabel43 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        St_Result_input = new javax.swing.JTabbedPane();
        jLabel4 = new javax.swing.JLabel();
        St_Result_Print = new javax.swing.JTabbedPane();
        jLabel5 = new javax.swing.JLabel();
        TeacherTab = new javax.swing.JTabbedPane();
        Te_home = new javax.swing.JTabbedPane();
        te_All = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        te_btn_report = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        te_btn_add = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        te_btn_rutines = new javax.swing.JButton();
        Te_add = new javax.swing.JTabbedPane();
        Te_ClassRutine = new javax.swing.JTabbedPane();
        Te_Full_Report = new javax.swing.JTabbedPane();
        Exam_Seduel = new javax.swing.JTabbedPane();
        ex_Home = new javax.swing.JTabbedPane();
        ex_date_input = new javax.swing.JTabbedPane();
        ex_view = new javax.swing.JTabbedPane();
        Payment = new javax.swing.JTabbedPane();
        Pay_home = new javax.swing.JTabbedPane();
        Pay_Stydent = new javax.swing.JTabbedPane();
        Pay_Teacher = new javax.swing.JTabbedPane();
        Pay_Staff = new javax.swing.JTabbedPane();
        Staff = new javax.swing.JTabbedPane();
        Staff_Home = new javax.swing.JTabbedPane();
        Staff_Add = new javax.swing.JTabbedPane();
        Staff_view = new javax.swing.JTabbedPane();
        ex = new javax.swing.JTabbedPane();
        ex1 = new javax.swing.JTabbedPane();
        ex2 = new javax.swing.JTabbedPane();
        ex3 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headPanal.setBackground(new java.awt.Color(255, 153, 153));
        headPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LALBAG MODEL SCHOOL AND COLLAGE , DHAKA-1212");
        headPanal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/schoolLOGO.png"))); // NOI18N
        headPanal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 80));

        mainPanal.add(headPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        optionPanal.setBackground(new java.awt.Color(153, 255, 204));
        optionPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(255, 153, 153));
        btnHome.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/home (1)_1.png"))); // NOI18N
        btnHome.setText("  HOME");
        btnHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 2));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        optionPanal.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 40));

        btnStudent.setBackground(new java.awt.Color(255, 153, 153));
        btnStudent.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/graduated.png"))); // NOI18N
        btnStudent.setText("STUDENT");
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        optionPanal.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 40));

        btnTeacher.setBackground(new java.awt.Color(255, 153, 153));
        btnTeacher.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/teaching.png"))); // NOI18N
        btnTeacher.setText("  TEACHER");
        btnTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTeacherMouseClicked(evt);
            }
        });
        optionPanal.add(btnTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 40));

        btnExam.setBackground(new java.awt.Color(255, 153, 153));
        btnExam.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnExam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/exam.png"))); // NOI18N
        btnExam.setText("    EXAM");
        btnExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExamMouseClicked(evt);
            }
        });
        optionPanal.add(btnExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 40));

        btnPayment.setBackground(new java.awt.Color(255, 153, 153));
        btnPayment.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/bill.png"))); // NOI18N
        btnPayment.setText(" PAYMENT");
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });
        optionPanal.add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        btnStaff.setBackground(new java.awt.Color(255, 153, 153));
        btnStaff.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 16)); // NOI18N
        btnStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/teamwork.png"))); // NOI18N
        btnStaff.setText("  STAFF");
        btnStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStaffMouseClicked(evt);
            }
        });
        optionPanal.add(btnStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 40));

        mainPanal.add(optionPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 560));

        bodyPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 280, 240));

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 270, 240));

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 270, 240));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, 240));

        jPanel9.setBackground(new java.awt.Color(255, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 280, 240));

        jPanel10.setBackground(new java.awt.Color(255, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 280, 240));

        homePanal.addTab("tab1", jPanel1);

        HomeTab.addTab("tab1", homePanal);

        mainTab.addTab("tab1", HomeTab);

        St_All.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_1.setBackground(new java.awt.Color(255, 153, 153));
        st_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        st_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                st_1MouseEntered(evt);
            }
        });
        st_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        St_btn_addmition.setText("ADMITION");
        St_btn_addmition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                St_btn_addmitionMouseClicked(evt);
            }
        });
        st_1.add(St_btn_addmition, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 50));

        jPanel13.add(st_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, 390));

        st_2.setBackground(new java.awt.Color(255, 153, 153));
        st_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        st_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        St_btn_Deatils.setText("STUDNT DEATIL'S");
        St_btn_Deatils.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                St_btn_DeatilsMouseClicked(evt);
            }
        });
        st_2.add(St_btn_Deatils, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 50));

        jPanel13.add(st_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 190, 390));

        st_3.setBackground(new java.awt.Color(255, 153, 153));
        st_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        st_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_btn_result_in.setText("RESULT INPUT");
        st_btn_result_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                st_btn_result_inMouseClicked(evt);
            }
        });
        st_3.add(st_btn_result_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, 50));

        jPanel13.add(st_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 200, 390));

        St_4.setBackground(new java.awt.Color(255, 153, 153));
        St_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        St_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_btn_result_out.setText("REAULT SHOW");
        st_btn_result_out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                st_btn_result_outMouseClicked(evt);
            }
        });
        St_4.add(st_btn_result_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 120, 50));

        jPanel13.add(St_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 190, 390));
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        St_All.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        St_Home.addTab("tab1", St_All);

        StudentTab.addTab("tab5", St_Home);

        St_Admition.setBackground(new java.awt.Color(255, 255, 255));

        st_admision_main_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        st_add.setBackground(new java.awt.Color(255, 255, 255));
        st_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Id", "Student Name", "Father Name", "Age", "Gender", "Phone no.", "Date of Birth"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Student.setViewportView(jTable1);

        st_add.add(Table_Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 407, 930, 150));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Action", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Fax", 1, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/st_1.png"))); // NOI18N
        jPanel14.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 140));

        jPanel11.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 140));

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton1.setText("Delete");
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 160, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton2.setText("Browse");
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton3.setText("Save");
        jPanel11.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton4.setText("Edit");
        jPanel11.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 160, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton5.setText("Update");
        jPanel11.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, 30));

        st_add.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 180, 380));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "STUDENT ADMISION FORM", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Fax", 1, 14))); // NOI18N
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Batch id");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Admision Class");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Relision");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, 20));

        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Student id");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, -1));

        jComboBox1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Class --", "CLASS__6", "CLASS__7", "CLASS__8", "CLASS__9", "CLASS__10", " " }));
        jPanel12.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 140, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("First Name");
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        jTextField6.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Parmanent Address");
        jPanel12.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        jTextField7.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Fathers Name");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 20));

        jTextField8.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Father Phone No");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 120, 20));

        jTextField9.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 150, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Mothers Name");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 20));

        jTextField10.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, -1));
        jPanel12.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 150, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Mothers Phone No");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 130, 20));

        jComboBox2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Select Blood Group", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel12.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 150, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Age");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 530, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Present Address");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 530, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Date of Birth");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 20));

        jTextField11.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("E-mail Address");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 150, 20));

        jTextField12.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 140, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Student Blood Group");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 150, 20));

        jTextField13.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Birth Certificate No:");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 150, 20));

        jComboBox3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Gender --", "Male", "Female" }));
        jPanel12.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Session Year");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 110, 20));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setText("Last Name");
        jPanel12.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 110, 20));
        jPanel12.add(jYearChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 140, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setText("Gender");
        jPanel12.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 130, 20));

        jTextField14.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Nationality");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 20));

        jTextField15.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jPanel12.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, -1));

        st_add.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 730, 380));

        st_admision_main_pan.add(st_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        St_Admition.addTab("tab1", st_admision_main_pan);

        StudentTab.addTab("tab1", St_Admition);

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel42.setText("Batch id");
        jPanel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 80, 30));
        jPanel16.add(jYearChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 30));

        jLabel43.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel43.setText("Session Year");
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 100, 30));

        jLabel44.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Class");
        jPanel16.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, 30));
        jPanel16.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 120, 30));

        jLabel51.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("Batch id");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 80, 30));
        jPanel16.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 120, 30));

        jButton6.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jButton6.setText("View");
        jPanel16.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 100, 30));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 970, 60));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Fax", 1, 12))); // NOI18N
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assate/st_1.png"))); // NOI18N
        jPanel19.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, 160));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 170));

        jLabel32.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel32.setText("Birth Certificate No");
        jPanel18.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 170, 30));

        jLabel33.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel33.setText("Full Name");
        jPanel18.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 30));

        jLabel34.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel34.setText("Father's Name");
        jPanel18.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 130, 30));

        jLabel35.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel35.setText("Mother's Name");
        jPanel18.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 140, 30));

        jLabel36.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel36.setText("Phone Number");
        jPanel18.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 30));

        jLabel38.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel38.setText("Date Of Birth");
        jPanel18.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 140, 30));

        jLabel39.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel39.setText("Age");
        jPanel18.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, 30));

        jLabel40.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel40.setText("Religion");
        jPanel18.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 140, 30));

        jLabel41.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel41.setText("Nationality");
        jPanel18.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 140, 30));

        jLabel45.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel45.setText("Phone Number");
        jPanel18.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, 30));

        jLabel46.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel46.setText("Email");
        jPanel18.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 140, 30));

        jLabel47.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel47.setText("Present Addess");
        jPanel18.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 140, 30));

        jLabel48.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel48.setText("Parmanent Address");
        jPanel18.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, 30));

        jLabel49.setFont(new java.awt.Font("Lucida Fax", 1, 16)); // NOI18N
        jLabel49.setText("Blood Group");
        jPanel18.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 120, 30));

        jLabel50.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel50.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 130, 30));

        jLabel52.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel52.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 190, 30));

        jLabel53.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel53.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 190, 30));

        jLabel54.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel54.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 190, 30));

        jLabel55.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel55.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 190, 30));

        jLabel56.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel56.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 190, 30));

        jLabel57.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel57.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 190, 30));

        jLabel58.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel58.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 30));

        jLabel59.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel59.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 190, 30));

        jLabel60.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel60.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 190, 30));

        jLabel61.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel61.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 190, 30));

        jLabel62.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel62.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 190, 30));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane1.setViewportView(jTextArea3);

        jPanel18.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 570, 30));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel18.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 570, 30));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 940, 440));

        jLabel12.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Class 10");
        jPanel17.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, 40));

        jLabel30.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Md Faysal");
        jPanel17.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        jLabel31.setFont(new java.awt.Font("Lucida Fax", 1, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Male");
        jPanel17.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 80, 40));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 970, 500));

        St_deatils.addTab("tab1", jPanel15);

        StudentTab.addTab("tab2", St_deatils);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REAULT INPUT");
        St_Result_input.addTab("tab1", jLabel4);

        StudentTab.addTab("tab3", St_Result_input);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESULT SHOW");
        St_Result_Print.addTab("tab1", jLabel5);

        StudentTab.addTab("tab4", St_Result_Print);

        mainTab.addTab("tab2", StudentTab);

        te_All.setBackground(new java.awt.Color(255, 255, 255));
        te_All.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        te_btn_report.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        te_btn_report.setText("TEACHER REPORT");
        te_btn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_btn_reportMouseClicked(evt);
            }
        });
        jPanel2.add(te_btn_report, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 890, 50));

        te_All.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 890, 230));

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        te_btn_add.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        te_btn_add.setText("NEW TEACHER INFURMATION ADD");
        te_btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_btn_addMouseClicked(evt);
            }
        });
        jPanel3.add(te_btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 420, 50));

        te_All.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 420, 230));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        te_btn_rutines.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        te_btn_rutines.setText("CLASS RUTINE AND TIME SEDUEL");
        te_btn_rutines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te_btn_rutinesMouseClicked(evt);
            }
        });
        te_btn_rutines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                te_btn_rutinesActionPerformed(evt);
            }
        });
        jPanel4.add(te_btn_rutines, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 430, 50));

        te_All.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 430, 230));

        Te_home.addTab("tab1", te_All);

        TeacherTab.addTab("tab4", Te_home);
        TeacherTab.addTab("tab1", Te_add);
        TeacherTab.addTab("tab2", Te_ClassRutine);
        TeacherTab.addTab("tab3", Te_Full_Report);

        mainTab.addTab("tab3", TeacherTab);

        Exam_Seduel.addTab("tab3", ex_Home);
        Exam_Seduel.addTab("tab1", ex_date_input);
        Exam_Seduel.addTab("tab2", ex_view);

        mainTab.addTab("tab4", Exam_Seduel);

        Payment.addTab("tab4", Pay_home);
        Payment.addTab("tab1", Pay_Stydent);
        Payment.addTab("tab2", Pay_Teacher);
        Payment.addTab("tab3", Pay_Staff);

        mainTab.addTab("tab5", Payment);

        Staff.addTab("tab3", Staff_Home);
        Staff.addTab("tab1", Staff_Add);
        Staff.addTab("tab2", Staff_view);

        mainTab.addTab("tab6", Staff);
        mainTab.addTab("tab7", ex);
        mainTab.addTab("tab8", ex1);
        mainTab.addTab("tab9", ex2);
        mainTab.addTab("tab10", ex3);

        bodyPanal.add(mainTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -90, 990, 660));

        mainPanal.add(bodyPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 970, 560));

        getContentPane().add(mainPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(0);
        StudentTab.setSelectedIndex(0);
        TeacherTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(1);
        StudentTab.setSelectedIndex(0);
         TeacherTab.setSelectedIndex(0);
         
    }//GEN-LAST:event_btnStudentMouseClicked

    private void btnTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacherMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(2);
        StudentTab.setSelectedIndex(0);
        TeacherTab.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnTeacherMouseClicked

    private void btnExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExamMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(3);
        StudentTab.setSelectedIndex(0);
        TeacherTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnExamMouseClicked

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(4);
        StudentTab.setSelectedIndex(0);
        TeacherTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnPaymentMouseClicked

    private void btnStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStaffMouseClicked
        // TODO add your handling code here:
        mainTab.setSelectedIndex(5);
        StudentTab.setSelectedIndex(0);
        TeacherTab.setSelectedIndex(0);
    }//GEN-LAST:event_btnStaffMouseClicked

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
         btnHome.setBackground(new Color(255, 153, 153));
    }//GEN-LAST:event_btnHomeMouseExited

    private void st_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_1MouseEntered
        // TODO add your handling code here:
//         .setBackground(Color.GREEN);
            
    }//GEN-LAST:event_st_1MouseEntered

    private void St_btn_addmitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_btn_addmitionMouseClicked
        // TODO add your handling code here:
       StudentTab.setSelectedIndex(1);
    }//GEN-LAST:event_St_btn_addmitionMouseClicked

    private void St_btn_DeatilsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_St_btn_DeatilsMouseClicked
        // TODO add your handling code here:
         StudentTab.setSelectedIndex(2);
    }//GEN-LAST:event_St_btn_DeatilsMouseClicked

    private void st_btn_result_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_btn_result_inMouseClicked
        // TODO add your handling code here:
         StudentTab.setSelectedIndex(3);
    }//GEN-LAST:event_st_btn_result_inMouseClicked

    private void st_btn_result_outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_st_btn_result_outMouseClicked
        // TODO add your handling code here:
         StudentTab.setSelectedIndex(4);
    }//GEN-LAST:event_st_btn_result_outMouseClicked

    private void te_btn_rutinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_te_btn_rutinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_te_btn_rutinesActionPerformed

    private void te_btn_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_btn_addMouseClicked
        // TODO add your handling code here:
        TeacherTab.setSelectedIndex(1);
    }//GEN-LAST:event_te_btn_addMouseClicked

    private void te_btn_rutinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_btn_rutinesMouseClicked
        // TODO add your handling code here:
        TeacherTab.setSelectedIndex(2);
    }//GEN-LAST:event_te_btn_rutinesMouseClicked

    private void te_btn_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te_btn_reportMouseClicked
        // TODO add your handling code here:
        TeacherTab.setSelectedIndex(3);
    }//GEN-LAST:event_te_btn_reportMouseClicked

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Exam_Seduel;
    private javax.swing.JTabbedPane HomeTab;
    private javax.swing.JTabbedPane Pay_Staff;
    private javax.swing.JTabbedPane Pay_Stydent;
    private javax.swing.JTabbedPane Pay_Teacher;
    private javax.swing.JTabbedPane Pay_home;
    private javax.swing.JTabbedPane Payment;
    private javax.swing.JPanel St_4;
    private javax.swing.JTabbedPane St_Admition;
    private javax.swing.JPanel St_All;
    private javax.swing.JTabbedPane St_Home;
    private javax.swing.JTabbedPane St_Result_Print;
    private javax.swing.JTabbedPane St_Result_input;
    private javax.swing.JButton St_btn_Deatils;
    private javax.swing.JButton St_btn_addmition;
    private javax.swing.JTabbedPane St_deatils;
    private javax.swing.JTabbedPane Staff;
    private javax.swing.JTabbedPane Staff_Add;
    private javax.swing.JTabbedPane Staff_Home;
    private javax.swing.JTabbedPane Staff_view;
    private javax.swing.JTabbedPane StudentTab;
    private javax.swing.JScrollPane Table_Student;
    private javax.swing.JTabbedPane Te_ClassRutine;
    private javax.swing.JTabbedPane Te_Full_Report;
    private javax.swing.JTabbedPane Te_add;
    private javax.swing.JTabbedPane Te_home;
    private javax.swing.JTabbedPane TeacherTab;
    private javax.swing.JPanel bodyPanal;
    private javax.swing.JButton btnExam;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnStaff;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnTeacher;
    private javax.swing.JTabbedPane ex;
    private javax.swing.JTabbedPane ex1;
    private javax.swing.JTabbedPane ex2;
    private javax.swing.JTabbedPane ex3;
    private javax.swing.JTabbedPane ex_Home;
    private javax.swing.JTabbedPane ex_date_input;
    private javax.swing.JTabbedPane ex_view;
    private javax.swing.JPanel headPanal;
    private javax.swing.JTabbedPane homePanal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    private javax.swing.JPanel mainPanal;
    private javax.swing.JTabbedPane mainTab;
    private javax.swing.JPanel optionPanal;
    private javax.swing.JPanel st_1;
    private javax.swing.JPanel st_2;
    private javax.swing.JPanel st_3;
    private javax.swing.JPanel st_add;
    private javax.swing.JPanel st_admision_main_pan;
    private javax.swing.JButton st_btn_result_in;
    private javax.swing.JButton st_btn_result_out;
    private javax.swing.JPanel te_All;
    private javax.swing.JButton te_btn_add;
    private javax.swing.JButton te_btn_report;
    private javax.swing.JButton te_btn_rutines;
    // End of variables declaration//GEN-END:variables
}
